### ISSUE TITLE
Circular import breaks `skyvern run server` on main (works on v1.0.47)

### ISSUE THREAD

**Issue by josephkehan-prog** [Skyvern-AI/skyvern#7762]
## Summary

`skyvern run server` fails to start on current `main` with a circular import. The same command works from the released `v1.0.47` wheel in an otherwise identical environment, so this is a regression introduced after the tag.

## Error

```
ImportError: cannot import name 'LLMAPIHandlerFactory' from partially initialized module
'skyvern.forge.sdk.api.llm.api_handler_factory'
(most likely due to a circular import)
```

Import chain from the traceback:

```
skyvern/cli/run_commands.py
  -> skyvern/forge/api_app.py
    -> skyvern/forge/forge_app.py
      -> skyvern/forge/agent.py
        -> skyvern/forge/sdk/api/llm/api_handler_factory.py  (partially initialized)
```

## Reproduce

```bash
git clone --depth 1 https://github.com/Skyvern-AI/skyvern.git
cd skyvern
uv venv --python 3.13 .venv
uv pip install -e ".[local,server]" --python .venv/bin/python
./.venv/bin/skyvern run server        # ImportError above
```

## Isolation

Importing the module on its own succeeds in the same venv — it only fails through the server entry point:

```
$ ./.venv/bin/python -c "import skyvern.forge.sdk.api.llm.api_handler_factory"
Registered OpenAI-compatible model with key OPENAI_COMPATIBLE model_name=...
# no error
```

And the released wheel imports the exact module that fails on `main`:

```
$ uv pip install "skyvern[server,local]==1.0.47"
$ python -c "import skyvern.forge.api_app; print('ok')"
ok
```

Same Python (3.13.14), same `.env`, same machine — only the source differs.

## Environment

- `main` @ `bc396d0` (which itself touched `api_handler_factory.py`)
- Released `v1.0.47` for comparison
- macOS arm64, CPython 3.13.14, installed with `uv`

## Note

`pyproject.toml` on `main` still reads `version = "1.0.47"`, so the broken tree is not distinguishable from the working release by version alone.

**Comment by AronPerez** [comment]
Thanks for the detailed report! We haven't been able to reproduce this yet. On current `main` (`d37078a8`) and on a clean archive of the exact commit referenced, `skyvern run server` completes imports and logs `Server started` via both the locked (`uv sync`) and unlocked (`uv pip install -e ".[local,server]"`) install paths; a direct `import skyvern.forge.api_app` also succeeds. One note: `bc396d0` doesn't actually touch `api_handler_factory.py` in this tree, so we may be looking at a different state than you were.

To help us reproduce, could you share:

1. The **full traceback** (all frames, not just the final `ImportError` line).
2. `uv pip freeze` from the failing venv (or at least the resolved versions of `litellm`, `instructor`, `pydantic`, `openai`, `anthropic`).
3. Exact Python patch version (e.g. `3.13.14`) and whether the failure is deterministic across fresh venvs.
4. The exact `git rev-parse HEAD` of the tree that fails.

Since this looks environment- or resolution-specific, that pin set will let us diff against a known-good resolve. Thanks!

**Comment by MilkyWay008** [comment]
Pretty sure that's a main-branch regression, not your setup - the import chain you traced goes right through the provider-registration refactor, so nothing uv or python on your side caused it. Released 1.0.47 wheel until it gets untangled is the sane move. If you do want to run off main, a lazy import inside `api_handler_factory` breaks the cycle, though your mileage may vary.
